spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_security?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


lanh:
  app:
    jwtSecret: bezKoderSecretKey
    jwtRefresh: bezKoderRefreshKey
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 120000